import * as XLSX from 'xlsx';
import * as fs from 'fs';
import * as path from 'path';
import { supabaseAdmin } from '../lib/supabase';
import { normalizeArabic } from '../lib/utils';

const BATCH_SIZE = 1000;

async function importExcelToSupabase() {
  try {
    console.log('🚀 Starting Excel to Supabase import...\n');
    
    // Read Excel file
    const excelPath = path.join(process.cwd(), 'ASC .xlsx');
    
    if (!fs.existsSync(excelPath)) {
      console.error('❌ Excel file not found at:', excelPath);
      process.exit(1);
    }

    console.log('📖 Reading Excel file...');
    const workbook = XLSX.readFile(excelPath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet);

    if (!data || data.length === 0) {
      console.error('❌ Excel file is empty');
      process.exit(1);
    }

    console.log(`✅ Found ${data.length} rows in Excel file\n`);

    // Show first row structure
    if (data.length > 0) {
      console.log('📋 Excel columns detected:');
      const firstRow = data[0] as any;
      const keys = Object.keys(firstRow);
      keys.forEach((key, idx) => {
        console.log(`  Column ${idx + 1} (${key}): "${firstRow[key]}"`);
      });
      console.log('');
    }

    console.log('✅ Column mapping:');
    console.log('   Column A (__EMPTY) → member_id');
    console.log('   Column B (__EMPTY_1) → name');
    console.log('   Column C (__EMPTY_2) → address');
    console.log('   Column D (__EMPTY_3) → job');
    console.log('   Column E (__EMPTY_4) → phone');
    console.log('   Column F (__EMPTY_5) → mobile\n');
    
    // Check if table exists
    console.log('🔍 Checking if tables exist in Supabase...');
    const { data: tableCheck, error: tableError } = await supabaseAdmin
      .from('members')
      .select('id')
      .limit(1);
    
    if (tableError && tableError.message.includes('not found')) {
      console.error('\n❌ ERROR: Tables do not exist in Supabase!');
      console.error('\n📋 Please create tables first:');
      console.error('   1. Go to Supabase Dashboard → SQL Editor');
      console.error('   2. Copy SQL from: scripts/create-supabase-tables.sql');
      console.error('   3. Paste and run in SQL Editor');
      console.error('   4. Then run this script again\n');
      process.exit(1);
    }
    
    console.log('✅ Tables exist, proceeding with import...\n');
    console.log('Processing rows...\n');

    const members: any[] = [];
    let skipped = 0;

    // Process each row
    for (let i = 0; i < data.length; i++) {
      const row = data[i] as any;
      
      // Map Excel columns A-F to proper field names
      const memberId = String(row['__EMPTY'] || '').trim();
      const name = String(row['__EMPTY_1'] || '').trim();
      const address = String(row['__EMPTY_2'] || '').trim();
      const job = String(row['__EMPTY_3'] || '').trim();
      const phone = String(row['__EMPTY_4'] || '').trim(); // Column E - landline
      const mobile = String(row['__EMPTY_5'] || '').trim(); // Column F - mobile
      
      // Skip rows without name
      if (!name || name.length === 0) {
        skipped++;
        continue;
      }

      // Create member object
      // Note: name_search, tokens, and search_vector will be auto-generated by trigger
      const member = {
        member_id: memberId,
        name: name,
        address: address || '',
        job: job || '',
        phone: phone || '',
        mobile: mobile || '',
        email: '',
        status: 'pending',
        notes: '',
        team_id: '',
        team_name: '',
      };

      members.push(member);

      // Progress indicator
      if ((i + 1) % 100 === 0) {
        console.log(`Processed ${i + 1}/${data.length} rows...`);
      }
    }

    console.log(`\n✅ Processed ${members.length} members (skipped ${skipped} rows)\n`);

    // Remove duplicates by member_id (keep first occurrence)
    console.log('🔍 Removing duplicate member_ids...');
    const uniqueMembers = new Map<string, any>();
    for (const member of members) {
      if (member.member_id && !uniqueMembers.has(member.member_id)) {
        uniqueMembers.set(member.member_id, member);
      }
    }
    const deduplicatedMembers = Array.from(uniqueMembers.values());
    console.log(`✅ Removed ${members.length - deduplicatedMembers.length} duplicates\n`);

    // Import to Supabase in batches
    console.log('📥 Importing to Supabase...\n');
    let imported = 0;
    let errors = 0;

    for (let i = 0; i < deduplicatedMembers.length; i += BATCH_SIZE) {
      const batch = deduplicatedMembers.slice(i, i + BATCH_SIZE);
      
      try {
        const { error } = await supabaseAdmin
          .from('members')
          .upsert(batch, { 
            onConflict: 'member_id',
            ignoreDuplicates: false
          });

        if (error) {
          // If batch upsert fails, try individual inserts
          console.log(`⚠️  Batch ${Math.floor(i / BATCH_SIZE) + 1} failed, trying individual inserts...`);
          let batchImported = 0;
          for (const member of batch) {
            const { error: singleError } = await supabaseAdmin
              .from('members')
              .upsert(member, { 
                onConflict: 'member_id',
                ignoreDuplicates: false
              });
            
            if (singleError) {
              errors++;
            } else {
              batchImported++;
            }
          }
          imported += batchImported;
          console.log(`✅ Imported ${batchImported}/${batch.length} from batch ${Math.floor(i / BATCH_SIZE) + 1}`);
        } else {
          imported += batch.length;
          console.log(`✅ Imported batch ${Math.floor(i / BATCH_SIZE) + 1}: ${imported}/${deduplicatedMembers.length} members`);
        }
      } catch (err: any) {
        console.error(`❌ Error importing batch ${Math.floor(i / BATCH_SIZE) + 1}:`, err.message);
        errors += batch.length;
      }

      // Small delay between batches
      if (i + BATCH_SIZE < deduplicatedMembers.length) {
        await new Promise(resolve => setTimeout(resolve, 500));
      }
    }

    console.log('\n✅ Import completed!');
    console.log(`📊 Total imported: ${imported} members`);
    console.log(`⏭️  Skipped: ${skipped} rows (no name found)`);
    console.log(`🔄 Duplicates removed: ${members.length - deduplicatedMembers.length} members`);
    console.log(`❌ Errors: ${errors} members`);
    console.log(`\n🎉 Data is now in Supabase with full-text search support!`);
    console.log('\n📝 Note: Search vectors will be automatically updated by database triggers.');
    
    process.exit(0);
  } catch (error: any) {
    console.error('❌ Import error:', error);
    process.exit(1);
  }
}

// Run the import
importExcelToSupabase();

